#This addition first creates the macro DEPS, which is the set of .h files on which the 
#.c files depend. Then we define a rule that applies to all files ending in the .o suffix. 
#The rule says that the .o file depends upon the .c version of the file and the .h files included in the 
#DEPS macro. The rule then says that to generate the .o file, make needs to compile the .c file using the compiler 
#defined in the CC macro. The -c flag says to generate the object file, the -o $@ says to put the output of the 
#compilation in the file named on the left side of the :, the $< is the first item in the dependencies list, and 
#the CFLAGS macro is defined as above.

#As a final simplification, let's use the special macros $@ and $^, which are the left and right sides of the :, 
#respectively, to make the overall compilation rule more general. In the example below, all of the include files 
#should be listed as part of the macro DEPS, and all of the object files should be listed as part of the macro OBJ.

CC=gcc
CFLAGS=-I. -Wall
DEPS = Grafo.h Pessoa.h
OBJ = main.o Grafo.o Pessoa.o

%.o: %.c $(DEPS)
	$(CC) -c -o $@ $< $(CFLAGS)

tp0: $(OBJ)
	gcc -o $@ $^ $(CFLAGS)
#impede de fazer algo com o arquivo chamado clean se tiver
.PHONY: clean
#limpa os *.o da pasta
clean:
	rm -f *.o 
